# Generated by Django 4.2.4 on 2023-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', to='review.genre'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
